### ISSUE TITLE
package compilation?

### ISSUE THREAD

**Issue by jimianelli** [BenWilliams-NOAA/surveyISS#10]
unsure if it's meant to compile, but when I try I get the following error:
Error: package or namespace load failed for ‘surveyISS’ in namespaceExport(ns, exports):
 undefined exports: ess_age, ess_caal, ess_size, match_gap_bs, query_data, srvy_comps_ai_rebs, srvy_iss_ai_rebs, srvy_iss_goa_dr, srvy_iss_goa_rebs

also, wonder if a readme or a vignette on how one runs this code would be possible?

**Comment by BenWilliams-NOAA** [comment]
yeah @pete-hulson has been tweaking a number of things so the packages hasn't been updated to reflect those yet. Will get to both aspects soon.

**Comment by pete-hulson** [comment]
ya, still developing (and all those throwing an error have been removed, but not in the namespace yet). however, if you'd like to play around check out the scripts in https://github.com/BenWilliams-NOAA/surveyISS/tree/main/dev/prod_scripts - these are for the production runs, and in 'run_surveyISS_prod_test.R' script you'll see some examples of how to run the functions (also has the special cases to check out too if you want)

**Comment by pete-hulson** [comment]
and @jimianelli - would like to hear you're input as we're still in the devel stage if you have time to play around with schtuff and things. i have a short list of things to add to it this year (like adding mean length & weight), another short list of things to add in the long run (like adding the ll survey)

**Comment by pete-hulson** [comment]
@jimianelli check 'er out now, would be interested to see if you have any issues running the package
