### ISSUE TITLE
proper call

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#14]
https://github.com/BenWilliams-NOAA/surveyISS/blob/3b65c71b41a152fe0aafbb09b7eb6b747f921b95/R/boot_haul.R#L14

this doesn't include `dplyr::` in the `group_by()` statement, also seems it should work with `.by = c(year, species_code)` on line 15 - or does sample get messed up? See the same issue in a number of functions.

**Comment by pete-hulson** [comment]
this has been changed to tidytable::mutate with .by rather than group_by
