### ISSUE TITLE
sample issues

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#15]
sample via tidyverse w/o using dplyr 

data.frame(a = c(1:10, NA, NA),
            b = c(NA, NA, 1:10)) %>% 
    tidytable::replace_na(list(a = -9, b=1)) %>% 
    tidytable::mutate(sex_ln_ag = sample(b, .N, replace = TRUE), .by = a)

**Comment by pete-hulson** [comment]
all these have been swapped over to tidytable::mutate and seems to be working like it should - i vaguely recall that the issue was in tidytable::summarise where the groupings got ignored
