### ISSUE TITLE
documentation cleanup

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#17]
all the `#' @returns` (i often delete this field) and `#' @examples` need some type of value - examples go in `\dontrun{age_error(age_date, r_t)}` - so that the code doesn't actually get processed when we build the package

**Comment by pete-hulson** [comment]
do you think we need anything in the `#' @examples` for fcns other than srvy_iss()?

**Comment by pete-hulson** [comment]
i think this has been addressed...
