### ISSUE TITLE
unclear

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#19]
https://github.com/BenWilliams-NOAA/surveyISS/blob/16ab0bc830f7e1780df7da3815328d1a2704d4a7/R/boot_age.R#L19
@pete-hulson i'm not sure why this is being joined to the same data but unsexed?

**Comment by pete-hulson** [comment]
what this is doing is making the samples all the same sex - i.e., combining the data to run for combined-sex comps prior to expansion (as opposed to summing the sex-specific comps after expansion). i went with sex = 0 to denote data combined prior to expansion, sex = 4 for comps combined after expansion, and then sex = 12 for comps that are sex-specific (females-males) but sum to 1 across sexes
