### ISSUE TITLE
no need

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#20]
https://github.com/BenWilliams-NOAA/surveyISS/blob/77264e892ece3270ab4429b576a8e787f65f7283/R/query_data.R#L21C17-L21C28

don't need to reference `surveyISS::` within the surveyISS package - check/build might give you a circular warning (not sure)

**Comment by pete-hulson** [comment]
ah, roger that, taken out
