### ISSUE TITLE
want more columns?

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#21]
https://github.com/BenWilliams-NOAA/surveyISS/blob/8c1ffef773b0237240866d47a9628ee2e82152de/R/query_data.R#L184

@pete-hulson this select is currently going to return just two columns, guessing you also want the `lat_mid` , `lon_mid` etc. 
can just `select` the columns desired, don't need the `-column_name`

**Comment by pete-hulson** [comment]
it seems to give me the columns i want when i run it - isn't this just removing those columns and then renaming the other two (while keeping all the other columns)?

**Comment by BenWilliams-NOAA** [comment]
odd behavior. select will only give you the cols you request

**Comment by pete-hulson** [comment]
roger that, happy to change it to select the columns we need

**Comment by pete-hulson** [comment]
done and one
