### ISSUE TITLE
time suck

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/surveyISS#4]
https://github.com/BenWilliams-NOAA/surveyISS/blob/99a634081b1164cccc3e576f2da80c90f1231b89/R/age_error.R#L31
this left_join takes some time to run, basically it's going through and adding the complete set of ages in the age_dat for each new_age sampled, to reduce this back to the same size data you need the slice_sample call just a couple lines down - not sure if there's a better way to match this data up. when we run the sample() call above, we've got all the sampled data we need, just need a more efficient way to join it with the original data... not gonna do an issue in that function, but it's the same when adding age-length variaibility

**Comment by BenWilliams-NOAA** [comment]
I updated the code and pushed it - worth noting that the full (data included) structure of what I'm basing this off of is below - seems worth showing how i'm cleaning the reader-tester file


```
age_dat <- read_csv("~/code/swo-analysis-age/data/specimen_goa.csv") 

vroom::vroom("C:/Users/Ben.Williams/downloads/reader_tester.csv") %>% 
  tidytable::rename_with(tolower) %>% 
  tidytable::select(read_age, test_age, age = final_age, species_code = race_code, common_name) %>% 
  tidytable::filter(test_age>0) -> r_t

age_dat %>% 
  tidytable::mutate.(id = .I) -> age_dat


age_dat %>% 
  tidytable::inner_join(
                r_t %>% 
                  tidytable::filter(.N >= 10, .by = c(age, species_code)) %>% 
                  tidytable::mutate(new_age = sample(test_age, .N, replace = TRUE), 
                                        .by = c(age, species_code))
                ) %>% 
  tidytable::slice_head(n = 1, .by = id) -> agerr
 
agerr %>% 
  tidytable::select(-age, age = new_age) %>% 
  tidytable::bind_rows(anti_join(age_dat, agerr, by = "id")) %>% 
  tidytable::select(-id)
```
