### ISSUE TITLE
region switch

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#5]
@pete-hulson as it stands this switch is mandatory (output is saved to it) so it should not be set to NULL - well, unless you want a folder named NULL? Should put some thought into where/how to store results - is the output/region the best option?

https://github.com/BenWilliams-NOAA/surveyISS/blob/60acefd79b127a36d7afed26f7e3137078a4ad03/R/srvy_iss_goa_rebs.R#L15

**Comment by pete-hulson** [comment]
good point, could be an error checker - if you get a 'NULL' folder you screwed something up - or, we could put in an error message that requires 'region' to run. i guess another option is to add '_region' somewhere in the file name, but man, that would mean a bunch of result files. i'm not married to any folder structure, but it seems to make sense to keep with how you've set it up, where it's output/region - and now with the experimental runs it's output/region/exp. at the end of that example script i set up some code that compiles all the results across regions & surveys into a single file to plop out into the main output folder

**Comment by pete-hulson** [comment]
i do think the output/region is the best option, as it leaves the main output folder for compiled results across region (as i see how we could dissemenate results to folks). that said, i went ahead and set the default to 'goa' (except for the ai fcns, which i set to 'ai')
