### ISSUE TITLE
formal argument

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/surveyISS#9]
https://github.com/BenWilliams-NOAA/surveyISS/blob/90605f994a2de4417ff4dbe28f9c052385fd4ffc/R/age_error.R#L18

@pete-hulson ‘TRUE’ and ‘FALSE’ are reserved words denoting logical constants in the R language

It would be best practice to use `if(isTRUE(nonpar)) {...`

**Comment by pete-hulson** [comment]
roger that, swapped out
